"""
analyzers/base.py — Abstract base class and shared types for all analyzers.

Every analyzer (Image, Audio, Video) implements BaseAnalyzer so the Fusion Engine
can treat them polymorphically. Fail-closed: if a model errors, analyzers must
return label="uncertain" with a clear error message — never a false-confidence guess.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, Literal, Optional

from pydantic import BaseModel, Field


# ── Shared type passed into every analyzer ─────────────────────────────────────

@dataclass(frozen=True)
class CloudinaryFileRef:
    """
    Lightweight reference to a file already uploaded to Cloudinary.
    Analyzers receive this instead of raw bytes to avoid holding large blobs in memory.
    raw_bytes is set as a fallback when Cloudinary upload fails, so analyzers
    can still run inference directly on the original file.
    """
    public_id: str
    secure_url: str
    resource_type: str          # "image" | "video" | "raw"
    format: str                 # e.g. "mp4", "jpg", "wav"
    duration: Optional[float]   # seconds; None for images
    raw_bytes: Optional[bytes] = None  # set when Cloudinary URL is unavailable


# ── Canonical output schema ────────────────────────────────────────────────────

class AnalyzerResult(BaseModel):
    """
    Canonical output from any analyzer module.
    The Fusion Engine consumes this type directly.
    """
    modality: Literal["image", "audio", "video"]
    label: Literal["real", "fake", "uncertain"]
    confidence: float = Field(..., ge=0.0, le=1.0, description="0.0 = real, 1.0 = fake")
    signals: Dict[str, float] = Field(
        ...,
        description="Named sub-scores, e.g. {'gan_fingerprint': 0.91, 'sensor_noise': 0.04}"
    )
    evidence_url: Optional[str] = Field(
        None,
        description="Cloudinary URL to heatmap, spectrogram, or annotated frame"
    )
    processing_time_ms: int = Field(..., ge=0)
    error_message: Optional[str] = Field(
        None,
        description="Set when label='uncertain' due to a model or processing error"
    )
    is_stub: bool = Field(
        False,
        description="True if output was generated by development stubs rather than real models"
    )
    stub_warning: Optional[str] = Field(
        None,
        description="Explicit disclaimer when running in development stub mode"
    )


# ── Abstract base ──────────────────────────────────────────────────────────────

class BaseAnalyzer(ABC):
    """
    All analyzer modules must implement this interface.

    Contract:
    - analyze() must never raise; it catches internal exceptions and returns
      label="uncertain" with error_message populated instead.
    - Model loading (if any) should happen in __init__ or a dedicated _load_model()
      classmethod so it runs once at startup, not per-request.
    """

    @abstractmethod
    async def analyze(self, file_ref: CloudinaryFileRef) -> AnalyzerResult:
        """
        Run inference on the given Cloudinary file reference.

        Args:
            file_ref: Reference to the uploaded file on Cloudinary.

        Returns:
            AnalyzerResult — always returns, never raises.
        """
        ...
